Calendar
kevlartest/step pull request #13
Opened 2020-08-07 16:32 UTC by kevlartest

* Implement an algorithm for scheduling a meeting given peoples' 'busy' times
* Account for optional attendees at meetings
* Add test to check if optional attendees are taken into account

2020-08-10 08:57 UTC, thomasogara requested changes

2020-08-10 08:57 UTC, thomasogara commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +import java.util.*;
No wildcard imports https://google.github.io/styleguide/javaguide.html#s3.3.1-wildcard-imports

2020-08-10 08:57 UTC, thomasogara commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    final int requestedDuration = ((int) request.getDuration());
is it necessary to cast the long to an int?

2020-08-10 08:57 UTC, thomasogara commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    System.out.println("ranges size: " + ranges.size());
This should probably be removed

2020-08-10 08:58 UTC, thomasogara commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    System.out.println("ranges size: " + ranges.size());
this comment is supposed to point to only line 57, the System.out.println() statement

2020-08-10 09:18 UTC, kevlartest commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +import java.util.*;
Interestingly enough, that was actually an IntelliJ setting. I have now changed it.

2020-08-10 09:19 UTC, kevlartest commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    final int requestedDuration = ((int) request.getDuration());
Well yes, because the entire API works with ints yet for some reason the duration is returned as long

2020-08-10 09:20 UTC, kevlartest commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    System.out.println("ranges size: " + ranges.size());
Yes, that was just for debugging

2020-08-10 09:30 UTC, thomasogara commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    final int requestedDuration = ((int) request.getDuration());
From my own scanning of the code, It looks as though requestedDuration is only ever used in calls to methods in the MeetingRequest class? Specifically, it's only ever used in checkViability(). In this method, it's only ever compared to a long, so I think it would make sense to store the value of request.getDuration() as a long, to avoid potential errors caused by truncating the long. (For example, if 2^32 where provided as the request duration, casting to an int would result in the duration being 0.)

2020-08-10 10:53 UTC, kevlartest commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    final int requestedDuration = ((int) request.getDuration());
The values in checkViability() are all integers, so that wouldn't be a problem. The issue is if the long contains a value larger than an int can hold, which while casting the int would end up having a negative value. For this reason, I have changed the cast to use [Math.toIntExact()](https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html#toIntExact-long-) instead, which will throw an exception if the long doesn't fit.

2020-08-11 16:59 UTC, thomasogara approved these changes

2020-08-12 09:02 UTC, magurmach requested changes

2020-08-12 10:34 UTC, gjrb commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +                                                    .add(event)));
+1

2020-08-12 10:36 UTC, gjrb commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +                      Math.max(eventEnd, end)); // Set new potential start to whichever meeting ends later
+1

2020-08-12 10:58 UTC, kevlartest commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +                                                    .add(event)));
I blame this on the Google code formatter splitting it up across multiple lines, but I have changed it to using for loops as it makes the intent much clearer.

2020-08-12 10:59 UTC, kevlartest commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +                      Math.max(eventEnd, end)); // Set new potential start to whichever meeting ends later
Indeed that was the case. I have moved the comment to above the code.

2020-08-17 10:28 UTC, gjrb approved these changes

2020-08-17 12:11 UTC, magurmach approved these changes

2020-08-17 12:25 UTC, merged